// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ad.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cascadeOfflineAds = `-- name: CascadeOfflineAds :exec
UPDATE ads SET status = 'offline', updated_at = now()
WHERE advertiser_id = $1 AND deleted_at IS NULL
`

// 广告商下架单向写级联：名下未删广告一并下架（重开不反向恢复）。
func (q *Queries) CascadeOfflineAds(ctx context.Context, advertiserID int64) error {
	_, err := q.db.Exec(ctx, cascadeOfflineAds, advertiserID)
	return err
}

const createAd = `-- name: CreateAd :one
INSERT INTO ads (advertiser_id, title, media_path, link, stock_total, stock_remaining, expires_at)
VALUES ($1, $2, $3, $4,
        $5, $5, $6)
RETURNING id, advertiser_id, title, media_path, link, stock_total, stock_remaining, status, deleted_at, created_at, updated_at, expires_at
`

type CreateAdParams struct {
	AdvertiserID int64
	Title        string
	MediaPath    string
	Link         *string
	Stock        int32
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) (Ad, error) {
	row := q.db.QueryRow(ctx, createAd,
		arg.AdvertiserID,
		arg.Title,
		arg.MediaPath,
		arg.Link,
		arg.Stock,
		arg.ExpiresAt,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Title,
		&i.MediaPath,
		&i.Link,
		&i.StockTotal,
		&i.StockRemaining,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createAdvertiser = `-- name: CreateAdvertiser :one
INSERT INTO advertisers (name, contact) VALUES ($1, $2) RETURNING id, name, contact, status, deleted_at, created_at, updated_at
`

type CreateAdvertiserParams struct {
	Name    string
	Contact *string
}

func (q *Queries) CreateAdvertiser(ctx context.Context, arg CreateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, createAdvertiser, arg.Name, arg.Contact)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementAdStock = `-- name: DecrementAdStock :execrows
UPDATE ads SET stock_remaining = stock_remaining - 1, updated_at = now()
WHERE id = $1 AND stock_remaining > 0
`

// 原子扣库存（条件 UPDATE 杜绝并发超投）；0 行 = 恰好被并发抢空，调用方重取/返空。
func (q *Queries) DecrementAdStock(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, decrementAdStock, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAdWatch = `-- name: InsertAdWatch :exec
INSERT INTO ad_watches (customer_id, ad_id) VALUES ($1, $2)
`

type InsertAdWatchParams struct {
	CustomerID int64
	AdID       int64
}

func (q *Queries) InsertAdWatch(ctx context.Context, arg InsertAdWatchParams) error {
	_, err := q.db.Exec(ctx, insertAdWatch, arg.CustomerID, arg.AdID)
	return err
}

const listAds = `-- name: ListAds :many
SELECT id, advertiser_id, title, media_path, link, stock_total, stock_remaining, status, deleted_at, created_at, updated_at, expires_at FROM ads WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListAds(ctx context.Context) ([]Ad, error) {
	rows, err := q.db.Query(ctx, listAds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ad
	for rows.Next() {
		var i Ad
		if err := rows.Scan(
			&i.ID,
			&i.AdvertiserID,
			&i.Title,
			&i.MediaPath,
			&i.Link,
			&i.StockTotal,
			&i.StockRemaining,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvertisers = `-- name: ListAdvertisers :many
SELECT id, name, contact, status, deleted_at, created_at, updated_at FROM advertisers WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListAdvertisers(ctx context.Context) ([]Advertiser, error) {
	rows, err := q.db.Query(ctx, listAdvertisers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Advertiser
	for rows.Next() {
		var i Advertiser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickServingAd = `-- name: PickServingAd :one
SELECT a.id, a.title, a.media_path, a.link FROM ads a
JOIN advertisers adv ON adv.id = a.advertiser_id
WHERE a.status = 'active' AND a.deleted_at IS NULL AND a.stock_remaining > 0
  AND (a.expires_at IS NULL OR a.expires_at > now())
  AND adv.status = 'active' AND adv.deleted_at IS NULL
ORDER BY random()
LIMIT 1
`

type PickServingAdRow struct {
	ID        int64
	Title     string
	MediaPath string
	Link      *string
}

// 随机取一条在投广告：四条件（广告上架 ∧ 广告商上架 ∧ 库存>0 ∧ 未过期）+ 均匀随机。
func (q *Queries) PickServingAd(ctx context.Context) (PickServingAdRow, error) {
	row := q.db.QueryRow(ctx, pickServingAd)
	var i PickServingAdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.MediaPath,
		&i.Link,
	)
	return i, err
}

const setAdStatus = `-- name: SetAdStatus :execrows
UPDATE ads SET status = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
`

type SetAdStatusParams struct {
	Status AdStatus
	ID     int64
}

func (q *Queries) SetAdStatus(ctx context.Context, arg SetAdStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAdvertiserStatus = `-- name: SetAdvertiserStatus :execrows
UPDATE advertisers SET status = $1, updated_at = now()
WHERE id = $2 AND deleted_at IS NULL
`

type SetAdvertiserStatusParams struct {
	Status AdStatus
	ID     int64
}

func (q *Queries) SetAdvertiserStatus(ctx context.Context, arg SetAdvertiserStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAdvertiserStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAd = `-- name: SoftDeleteAd :execrows
UPDATE ads SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAd(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAd, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAd = `-- name: UpdateAd :one
UPDATE ads
SET title = COALESCE($1, title),
    media_path = COALESCE($2, media_path),
    link = COALESCE($3, link),
    expires_at = COALESCE($4, expires_at),
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, advertiser_id, title, media_path, link, stock_total, stock_remaining, status, deleted_at, created_at, updated_at, expires_at
`

type UpdateAdParams struct {
	Title     *string
	MediaPath *string
	Link      *string
	ExpiresAt pgtype.Timestamptz
	ID        int64
}

func (q *Queries) UpdateAd(ctx context.Context, arg UpdateAdParams) (Ad, error) {
	row := q.db.QueryRow(ctx, updateAd,
		arg.Title,
		arg.MediaPath,
		arg.Link,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Ad
	err := row.Scan(
		&i.ID,
		&i.AdvertiserID,
		&i.Title,
		&i.MediaPath,
		&i.Link,
		&i.StockTotal,
		&i.StockRemaining,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateAdvertiser = `-- name: UpdateAdvertiser :one
UPDATE advertisers
SET name = COALESCE($1, name),
    contact = COALESCE($2, contact),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, contact, status, deleted_at, created_at, updated_at
`

type UpdateAdvertiserParams struct {
	Name    *string
	Contact *string
	ID      int64
}

func (q *Queries) UpdateAdvertiser(ctx context.Context, arg UpdateAdvertiserParams) (Advertiser, error) {
	row := q.db.QueryRow(ctx, updateAdvertiser, arg.Name, arg.Contact, arg.ID)
	var i Advertiser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
