// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admins WHERE deleted_at IS NULL
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (username, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, password_changed_at, role, status, last_login_at, deleted_at, created_at, updated_at
`

type CreateAdminParams struct {
	Username     string
	PasswordHash string
	Role         AdminRole
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Username, arg.PasswordHash, arg.Role)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, username, password_hash, password_changed_at, role, status, last_login_at, deleted_at, created_at, updated_at FROM admins WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAdminByID(ctx context.Context, id int64) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, password_changed_at, role, status, last_login_at, deleted_at, created_at, updated_at FROM admins WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Role,
		&i.Status,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAdminLastLogin = `-- name: SetAdminLastLogin :exec
UPDATE admins SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetAdminLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setAdminLastLogin, id)
	return err
}
