// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bankcard.sql

package db

import (
	"context"
)

const insertBankCard = `-- name: InsertBankCard :one
INSERT INTO bank_cards (customer_id, card_no, holder_name, bank_name, bank_code, province, city)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, customer_id, card_no, holder_name, bank_name, bank_code, province, city, deleted_at, created_at, updated_at
`

type InsertBankCardParams struct {
	CustomerID int64
	CardNo     string
	HolderName string
	BankName   string
	BankCode   *string
	Province   *string
	City       *string
}

func (q *Queries) InsertBankCard(ctx context.Context, arg InsertBankCardParams) (BankCard, error) {
	row := q.db.QueryRow(ctx, insertBankCard,
		arg.CustomerID,
		arg.CardNo,
		arg.HolderName,
		arg.BankName,
		arg.BankCode,
		arg.Province,
		arg.City,
	)
	var i BankCard
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CardNo,
		&i.HolderName,
		&i.BankName,
		&i.BankCode,
		&i.Province,
		&i.City,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBankCards = `-- name: ListBankCards :many
SELECT id, customer_id, card_no, holder_name, bank_name, bank_code, province, city, deleted_at, created_at, updated_at FROM bank_cards
WHERE customer_id = $1 AND deleted_at IS NULL
ORDER BY id DESC
`

func (q *Queries) ListBankCards(ctx context.Context, customerID int64) ([]BankCard, error) {
	rows, err := q.db.Query(ctx, listBankCards, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankCard
	for rows.Next() {
		var i BankCard
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CardNo,
			&i.HolderName,
			&i.BankName,
			&i.BankCode,
			&i.Province,
			&i.City,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBankCard = `-- name: SoftDeleteBankCard :execrows
UPDATE bank_cards SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND customer_id = $2 AND deleted_at IS NULL
`

type SoftDeleteBankCardParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) SoftDeleteBankCard(ctx context.Context, arg SoftDeleteBankCardParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteBankCard, arg.ID, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
