// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package db

import (
	"context"
)

const getInviteValidReward = `-- name: GetInviteValidReward :one
SELECT reward FROM activity_reward_configs
WHERE kind = 'invite_valid' AND threshold = 0 AND enabled
`

// 邀请有效奖励金额：缺行或停用返回 ErrNoRows，调用方按"不发放"处理。
func (q *Queries) GetInviteValidReward(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getInviteValidReward)
	var reward int64
	err := row.Scan(&reward)
	return reward, err
}

const getVipInviteRewardCap = `-- name: GetVipInviteRewardCap :one
SELECT invite_reward_cap FROM vip_level_configs WHERE level = $1
`

// VIP 档邀请奖励上限；四档为种子数据，缺行即数据异常。
func (q *Queries) GetVipInviteRewardCap(ctx context.Context, level int32) (int64, error) {
	row := q.db.QueryRow(ctx, getVipInviteRewardCap, level)
	var invite_reward_cap int64
	err := row.Scan(&invite_reward_cap)
	return invite_reward_cap, err
}
