// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (public_id, username, password_hash, invite_code, inviter_id, ancestors)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at
`

type CreateCustomerParams struct {
	PublicID     string
	Username     string
	PasswordHash string
	InviteCode   string
	InviterID    *int64
	Ancestors    []int64
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.PublicID,
		arg.Username,
		arg.PasswordHash,
		arg.InviteCode,
		arg.InviterID,
		arg.Ancestors,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
