// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"
)

const countValidInvitees = `-- name: CountValidInvitees :one
SELECT COUNT(*) FROM customers
WHERE inviter_id = $1 AND valid_at IS NOT NULL AND deleted_at IS NULL
`

func (q *Queries) CountValidInvitees(ctx context.Context, inviterID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countValidInvitees, inviterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (public_id, username, password_hash, invite_code, inviter_id, ancestors)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at
`

type CreateCustomerParams struct {
	PublicID     string
	Username     string
	PasswordHash string
	InviteCode   string
	InviterID    *int64
	Ancestors    []int64
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.PublicID,
		arg.Username,
		arg.PasswordHash,
		arg.InviteCode,
		arg.InviterID,
		arg.Ancestors,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at FROM customers WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByInviteCode = `-- name: GetCustomerByInviteCode :one
SELECT id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at FROM customers WHERE invite_code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByInviteCode(ctx context.Context, inviteCode string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByInviteCode, inviteCode)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPublicID = `-- name: GetCustomerByPublicID :one
SELECT id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at FROM customers WHERE public_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByPublicID(ctx context.Context, publicID string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPublicID, publicID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByUsername = `-- name: GetCustomerByUsername :one
SELECT id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at FROM customers WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByUsername(ctx context.Context, username string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByUsername, username)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInviteCount = `-- name: IncrementInviteCount :exec
UPDATE customers SET invite_count = invite_count + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) IncrementInviteCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementInviteCount, id)
	return err
}

const markCustomerValidIfQualified = `-- name: MarkCustomerValidIfQualified :one
UPDATE customers
SET valid_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
  AND valid_at IS NULL
  AND video_count > 0
  AND invite_count > 0
  AND (phone IS NOT NULL OR email IS NOT NULL)
RETURNING inviter_id
`

// 有效用户判定（CAS）：三条件全下沉 SQL 原子完成，valid_at IS NULL 保证只翻转一次、永不回退。
// 返回 inviter_id 供翻转事务内给邀请人发奖；未翻转返回 ErrNoRows。
func (q *Queries) MarkCustomerValidIfQualified(ctx context.Context, id int64) (*int64, error) {
	row := q.db.QueryRow(ctx, markCustomerValidIfQualified, id)
	var inviter_id *int64
	err := row.Scan(&inviter_id)
	return inviter_id, err
}

const setCustomerLastLogin = `-- name: SetCustomerLastLogin :exec
UPDATE customers SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SetCustomerLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setCustomerLastLogin, id)
	return err
}

const updateCustomerPassword = `-- name: UpdateCustomerPassword :exec
UPDATE customers
SET password_hash = $2, password_changed_at = now(), updated_at = now()
WHERE id = $1
`

type UpdateCustomerPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) error {
	_, err := q.db.Exec(ctx, updateCustomerPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :one
UPDATE customers
SET name       = COALESCE($1, name),
    signature  = COALESCE($2, signature),
    email      = COALESCE($3, email),
    phone      = COALESCE($4, phone),
    updated_at = now()
WHERE id = $5
RETURNING id, public_id, username, password_hash, password_changed_at, name, phone, email, avatar_path, signature, invite_code, inviter_id, ancestors, valid_at, vip_level, status, withdrawal_password_hash, video_count, invite_count, follower_count, following_count, last_login_at, deleted_at, created_at, updated_at
`

type UpdateCustomerProfileParams struct {
	Name      *string
	Signature *string
	Email     *string
	Phone     *string
	ID        int64
}

func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerProfile,
		arg.Name,
		arg.Signature,
		arg.Email,
		arg.Phone,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Username,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AvatarPath,
		&i.Signature,
		&i.InviteCode,
		&i.InviterID,
		&i.Ancestors,
		&i.ValidAt,
		&i.VipLevel,
		&i.Status,
		&i.WithdrawalPasswordHash,
		&i.VideoCount,
		&i.InviteCount,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
