// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpVideoCounters = `-- name: BumpVideoCounters :exec
UPDATE videos
SET click_count      = click_count + $2,
    valid_play_count = valid_play_count + $3,
    like_count       = like_count + $4,
    comment_count    = comment_count + $5,
    hot_score        = hot_score + $6,
    updated_at       = now()
WHERE id = $1
`

type BumpVideoCountersParams struct {
	ID           int64
	ClickDelta   int64
	ValidDelta   int64
	LikeDelta    int64
	CommentDelta int64
	HotDelta     int64
}

// 通用计数与热度原子累计（ADR-0004：计数=原子条件 UPDATE；热度只增不减由调用方保证 delta >= 0）
func (q *Queries) BumpVideoCounters(ctx context.Context, arg BumpVideoCountersParams) error {
	_, err := q.db.Exec(ctx, bumpVideoCounters,
		arg.ID,
		arg.ClickDelta,
		arg.ValidDelta,
		arg.LikeDelta,
		arg.CommentDelta,
		arg.HotDelta,
	)
	return err
}

const insertComment = `-- name: InsertComment :one
INSERT INTO comments (video_id, customer_id, content, comment_date)
VALUES ($1, $2, $3, $4)
RETURNING id, video_id, customer_id, content, comment_date, deleted_at, created_at
`

type InsertCommentParams struct {
	VideoID     int64
	CustomerID  int64
	Content     string
	CommentDate pgtype.Date
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, insertComment,
		arg.VideoID,
		arg.CustomerID,
		arg.Content,
		arg.CommentDate,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.CustomerID,
		&i.Content,
		&i.CommentDate,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertLike = `-- name: InsertLike :execrows
INSERT INTO likes (customer_id, video_id) VALUES ($1, $2)
ON CONFLICT (customer_id, video_id) DO NOTHING
`

type InsertLikeParams struct {
	CustomerID int64
	VideoID    int64
}

func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLike, arg.CustomerID, arg.VideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPlay = `-- name: InsertPlay :one
INSERT INTO plays (customer_id, video_id) VALUES ($1, $2)
RETURNING id, customer_id, video_id, played_at, valid_at
`

type InsertPlayParams struct {
	CustomerID int64
	VideoID    int64
}

func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) (Play, error) {
	row := q.db.QueryRow(ctx, insertPlay, arg.CustomerID, arg.VideoID)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VideoID,
		&i.PlayedAt,
		&i.ValidAt,
	)
	return i, err
}

const listVideoComments = `-- name: ListVideoComments :many
SELECT c.id, c.content, c.created_at,
       cust.public_id AS author_public_id, cust.username AS author_username
FROM comments c
JOIN customers cust ON cust.id = c.customer_id
WHERE c.video_id = $1 AND c.deleted_at IS NULL
  AND ($2::bigint = 0 OR c.id < $2)
ORDER BY c.id DESC
LIMIT $3
`

type ListVideoCommentsParams struct {
	VideoID  int64
	Cursor   int64
	RowLimit int32
}

type ListVideoCommentsRow struct {
	ID             int64
	Content        string
	CreatedAt      pgtype.Timestamptz
	AuthorPublicID string
	AuthorUsername string
}

func (q *Queries) ListVideoComments(ctx context.Context, arg ListVideoCommentsParams) ([]ListVideoCommentsRow, error) {
	rows, err := q.db.Query(ctx, listVideoComments, arg.VideoID, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVideoCommentsRow
	for rows.Next() {
		var i ListVideoCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorPublicID,
			&i.AuthorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlayValid = `-- name: MarkPlayValid :one
UPDATE plays SET valid_at = now()
WHERE id = $1 AND customer_id = $2 AND valid_at IS NULL
RETURNING video_id
`

type MarkPlayValidParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) MarkPlayValid(ctx context.Context, arg MarkPlayValidParams) (int64, error) {
	row := q.db.QueryRow(ctx, markPlayValid, arg.ID, arg.CustomerID)
	var video_id int64
	err := row.Scan(&video_id)
	return video_id, err
}

const reviveLike = `-- name: ReviveLike :execrows
UPDATE likes SET deleted_at = NULL
WHERE customer_id = $1 AND video_id = $2 AND deleted_at IS NOT NULL
`

type ReviveLikeParams struct {
	CustomerID int64
	VideoID    int64
}

func (q *Queries) ReviveLike(ctx context.Context, arg ReviveLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviveLike, arg.CustomerID, arg.VideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteComment = `-- name: SoftDeleteComment :one
UPDATE comments SET deleted_at = now()
WHERE id = $1 AND customer_id = $2 AND deleted_at IS NULL
RETURNING video_id
`

type SoftDeleteCommentParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteComment, arg.ID, arg.CustomerID)
	var video_id int64
	err := row.Scan(&video_id)
	return video_id, err
}

const softDeleteLike = `-- name: SoftDeleteLike :execrows
UPDATE likes SET deleted_at = now()
WHERE customer_id = $1 AND video_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLikeParams struct {
	CustomerID int64
	VideoID    int64
}

func (q *Queries) SoftDeleteLike(ctx context.Context, arg SoftDeleteLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLike, arg.CustomerID, arg.VideoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
