// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityRewardKind string

const (
	ActivityRewardKindDaily       ActivityRewardKind = "daily"
	ActivityRewardKindMilestone   ActivityRewardKind = "milestone"
	ActivityRewardKindInviteValid ActivityRewardKind = "invite_valid"
)

func (e *ActivityRewardKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityRewardKind(s)
	case string:
		*e = ActivityRewardKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityRewardKind: %T", src)
	}
	return nil
}

type NullActivityRewardKind struct {
	ActivityRewardKind ActivityRewardKind
	Valid              bool // Valid is true if ActivityRewardKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityRewardKind) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityRewardKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityRewardKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityRewardKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityRewardKind), nil
}

type AdStatus string

const (
	AdStatusActive  AdStatus = "active"
	AdStatusOffline AdStatus = "offline"
)

func (e *AdStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdStatus(s)
	case string:
		*e = AdStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdStatus: %T", src)
	}
	return nil
}

type NullAdStatus struct {
	AdStatus AdStatus
	Valid    bool // Valid is true if AdStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdStatus), nil
}

type AdminRole string

const (
	AdminRoleAdmin  AdminRole = "admin"
	AdminRoleNormal AdminRole = "normal"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole
	Valid     bool // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

type AdminStatus string

const (
	AdminStatusActive   AdminStatus = "active"
	AdminStatusDisabled AdminStatus = "disabled"
)

func (e *AdminStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminStatus(s)
	case string:
		*e = AdminStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminStatus: %T", src)
	}
	return nil
}

type NullAdminStatus struct {
	AdminStatus AdminStatus
	Valid       bool // Valid is true if AdminStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdminStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminStatus), nil
}

type ClaimStatus string

const (
	ClaimStatusClaimed   ClaimStatus = "claimed"
	ClaimStatusSubmitted ClaimStatus = "submitted"
	ClaimStatusApproved  ClaimStatus = "approved"
	ClaimStatusRewarded  ClaimStatus = "rewarded"
	ClaimStatusRejected  ClaimStatus = "rejected"
	ClaimStatusExpired   ClaimStatus = "expired"
)

func (e *ClaimStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClaimStatus(s)
	case string:
		*e = ClaimStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClaimStatus: %T", src)
	}
	return nil
}

type NullClaimStatus struct {
	ClaimStatus ClaimStatus
	Valid       bool // Valid is true if ClaimStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClaimStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClaimStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClaimStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClaimStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClaimStatus), nil
}

type CustomerStatus string

const (
	CustomerStatusActive CustomerStatus = "active"
	CustomerStatusBanned CustomerStatus = "banned"
)

func (e *CustomerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomerStatus(s)
	case string:
		*e = CustomerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomerStatus: %T", src)
	}
	return nil
}

type NullCustomerStatus struct {
	CustomerStatus CustomerStatus
	Valid          bool // Valid is true if CustomerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CustomerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomerStatus), nil
}

type PaymentEventDirection string

const (
	PaymentEventDirectionRequest  PaymentEventDirection = "request"
	PaymentEventDirectionResponse PaymentEventDirection = "response"
	PaymentEventDirectionCallback PaymentEventDirection = "callback"
	PaymentEventDirectionQuery    PaymentEventDirection = "query"
)

func (e *PaymentEventDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentEventDirection(s)
	case string:
		*e = PaymentEventDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentEventDirection: %T", src)
	}
	return nil
}

type NullPaymentEventDirection struct {
	PaymentEventDirection PaymentEventDirection
	Valid                 bool // Valid is true if PaymentEventDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentEventDirection) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentEventDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentEventDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentEventDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentEventDirection), nil
}

type RankingPeriod string

const (
	RankingPeriodWeekly  RankingPeriod = "weekly"
	RankingPeriodMonthly RankingPeriod = "monthly"
)

func (e *RankingPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RankingPeriod(s)
	case string:
		*e = RankingPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for RankingPeriod: %T", src)
	}
	return nil
}

type NullRankingPeriod struct {
	RankingPeriod RankingPeriod
	Valid         bool // Valid is true if RankingPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRankingPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.RankingPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RankingPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRankingPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RankingPeriod), nil
}

type RechargeOrderStatus string

const (
	RechargeOrderStatusPendingPayment RechargeOrderStatus = "pending_payment"
	RechargeOrderStatusSucceeded      RechargeOrderStatus = "succeeded"
	RechargeOrderStatusFailed         RechargeOrderStatus = "failed"
	RechargeOrderStatusCancelled      RechargeOrderStatus = "cancelled"
)

func (e *RechargeOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RechargeOrderStatus(s)
	case string:
		*e = RechargeOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RechargeOrderStatus: %T", src)
	}
	return nil
}

type NullRechargeOrderStatus struct {
	RechargeOrderStatus RechargeOrderStatus
	Valid               bool // Valid is true if RechargeOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRechargeOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RechargeOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RechargeOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRechargeOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RechargeOrderStatus), nil
}

type TaskCategory string

const (
	TaskCategoryWatchVideo   TaskCategory = "watch_video"
	TaskCategoryUploadVideo  TaskCategory = "upload_video"
	TaskCategoryShareVideo   TaskCategory = "share_video"
	TaskCategoryComment      TaskCategory = "comment"
	TaskCategoryLike         TaskCategory = "like"
	TaskCategoryLogin        TaskCategory = "login"
	TaskCategoryInviteFriend TaskCategory = "invite_friend"
	TaskCategoryWatchAd      TaskCategory = "watch_ad"
)

func (e *TaskCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskCategory(s)
	case string:
		*e = TaskCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskCategory: %T", src)
	}
	return nil
}

type NullTaskCategory struct {
	TaskCategory TaskCategory
	Valid        bool // Valid is true if TaskCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskCategory) Scan(value interface{}) error {
	if value == nil {
		ns.TaskCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskCategory), nil
}

type TaskPeriod string

const (
	TaskPeriodDaily   TaskPeriod = "daily"
	TaskPeriodWeekly  TaskPeriod = "weekly"
	TaskPeriodMonthly TaskPeriod = "monthly"
)

func (e *TaskPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskPeriod(s)
	case string:
		*e = TaskPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskPeriod: %T", src)
	}
	return nil
}

type NullTaskPeriod struct {
	TaskPeriod TaskPeriod
	Valid      bool // Valid is true if TaskPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.TaskPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskPeriod), nil
}

type TransactionType string

const (
	TransactionTypeRecharge           TransactionType = "recharge"
	TransactionTypeWithdrawal         TransactionType = "withdrawal"
	TransactionTypeWatchReward        TransactionType = "watch_reward"
	TransactionTypePeriodicTaskReward TransactionType = "periodic_task_reward"
	TransactionTypeClaimTaskReward    TransactionType = "claim_task_reward"
	TransactionTypeSignInReward       TransactionType = "sign_in_reward"
	TransactionTypeMilestoneReward    TransactionType = "milestone_reward"
	TransactionTypeInviteValidReward  TransactionType = "invite_valid_reward"
	TransactionTypeContentReward      TransactionType = "content_reward"
	TransactionTypeVipPurchase        TransactionType = "vip_purchase"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type TranscodeJobStatus string

const (
	TranscodeJobStatusQueued    TranscodeJobStatus = "queued"
	TranscodeJobStatusRunning   TranscodeJobStatus = "running"
	TranscodeJobStatusSucceeded TranscodeJobStatus = "succeeded"
	TranscodeJobStatusFailed    TranscodeJobStatus = "failed"
)

func (e *TranscodeJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscodeJobStatus(s)
	case string:
		*e = TranscodeJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscodeJobStatus: %T", src)
	}
	return nil
}

type NullTranscodeJobStatus struct {
	TranscodeJobStatus TranscodeJobStatus
	Valid              bool // Valid is true if TranscodeJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscodeJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TranscodeJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscodeJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscodeJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscodeJobStatus), nil
}

type VideoStatus string

const (
	VideoStatusPendingTranscode VideoStatus = "pending_transcode"
	VideoStatusTranscoding      VideoStatus = "transcoding"
	VideoStatusPendingReview    VideoStatus = "pending_review"
	VideoStatusPublished        VideoStatus = "published"
	VideoStatusRejected         VideoStatus = "rejected"
	VideoStatusTranscodeFailed  VideoStatus = "transcode_failed"
)

func (e *VideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoStatus(s)
	case string:
		*e = VideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoStatus: %T", src)
	}
	return nil
}

type NullVideoStatus struct {
	VideoStatus VideoStatus
	Valid       bool // Valid is true if VideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoStatus), nil
}

type WithdrawalOrderStatus string

const (
	WithdrawalOrderStatusPendingReview WithdrawalOrderStatus = "pending_review"
	WithdrawalOrderStatusRejected      WithdrawalOrderStatus = "rejected"
	WithdrawalOrderStatusPaying        WithdrawalOrderStatus = "paying"
	WithdrawalOrderStatusSucceeded     WithdrawalOrderStatus = "succeeded"
	WithdrawalOrderStatusFailed        WithdrawalOrderStatus = "failed"
)

func (e *WithdrawalOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WithdrawalOrderStatus(s)
	case string:
		*e = WithdrawalOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WithdrawalOrderStatus: %T", src)
	}
	return nil
}

type NullWithdrawalOrderStatus struct {
	WithdrawalOrderStatus WithdrawalOrderStatus
	Valid                 bool // Valid is true if WithdrawalOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWithdrawalOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WithdrawalOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WithdrawalOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWithdrawalOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WithdrawalOrderStatus), nil
}

type ActivityRewardConfig struct {
	ID        int64
	Kind      ActivityRewardKind
	Threshold int32
	Reward    int64
	Enabled   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Ad struct {
	ID             int64
	AdvertiserID   int64
	Title          string
	MediaPath      string
	Link           *string
	StockTotal     int32
	StockRemaining int32
	Status         AdStatus
	DeletedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AdWatch struct {
	ID         int64
	CustomerID int64
	AdID       int64
	CreatedAt  pgtype.Timestamptz
}

type Admin struct {
	ID                int64
	Username          string
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
	Role              AdminRole
	Status            AdminStatus
	LastLoginAt       pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Advertiser struct {
	ID        int64
	Name      string
	Contact   *string
	Status    AdStatus
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type BankCard struct {
	ID         int64
	CustomerID int64
	CardNo     string
	HolderName string
	BankName   string
	BankCode   *string
	Province   *string
	City       *string
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ClaimTask struct {
	ID           int64
	Name         string
	Description  *string
	IconPath     *string
	MinVipLevel  int32
	Reward       int64
	Requirement  *string
	Flow         *string
	Link         *string
	DisplayOrder int32
	Enabled      bool
	StartsAt     pgtype.Timestamptz
	EndsAt       pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Comment struct {
	ID          int64
	VideoID     int64
	CustomerID  int64
	Content     string
	CommentDate pgtype.Date
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Customer struct {
	ID                     int64
	PublicID               string
	Username               string
	PasswordHash           string
	PasswordChangedAt      pgtype.Timestamptz
	Name                   *string
	Phone                  *string
	Email                  *string
	AvatarPath             *string
	Signature              *string
	InviteCode             string
	InviterID              *int64
	Ancestors              []int64
	ValidAt                pgtype.Timestamptz
	VipLevel               int32
	Status                 CustomerStatus
	WithdrawalPasswordHash *string
	VideoCount             int32
	InviteCount            int32
	FollowerCount          int32
	FollowingCount         int32
	LastLoginAt            pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type DailyActive struct {
	CustomerID int64
	ActiveDate pgtype.Date
}

type Follow struct {
	ID         int64
	FollowerID int64
	FolloweeID int64
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Like struct {
	ID         int64
	CustomerID int64
	VideoID    int64
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type MilestoneAward struct {
	ID           int64
	CustomerID   int64
	Month        pgtype.Date
	Threshold    int32
	RewardAmount int64
	CreatedAt    pgtype.Timestamptz
}

type PaymentEvent struct {
	ID        int64
	OrderNo   string
	Provider  string
	Direction PaymentEventDirection
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

type PeriodicTask struct {
	ID           int64
	Name         string
	Description  *string
	IconPath     *string
	Category     TaskCategory
	Period       TaskPeriod
	Target       int32
	Reward       int64
	DisplayOrder int32
	Enabled      bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type PeriodicTaskProgress struct {
	ID              int64
	CustomerID      int64
	TaskID          int64
	PeriodKey       string
	Progress        int32
	Target          int32
	CompletedAt     pgtype.Timestamptz
	RewardGrantedAt pgtype.Timestamptz
	RewardAmount    *int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Play struct {
	ID         int64
	CustomerID int64
	VideoID    int64
	PlayedAt   pgtype.Timestamptz
	ValidAt    pgtype.Timestamptz
}

type Ranking struct {
	ID          int64
	Period      RankingPeriod
	PeriodStart pgtype.Date
	Rank        int32
	VideoID     int64
	Score       int64
	CreatedAt   pgtype.Timestamptz
}

type RechargeOrder struct {
	ID              int64
	OrderNo         string
	CustomerID      int64
	Amount          int64
	FiatAmount      int64
	Currency        string
	PaymentMethod   *string
	Provider        *string
	ProviderOrderNo *string
	ProviderStatus  *string
	Status          RechargeOrderStatus
	FailureCode     *string
	FailureReason   *string
	ExpiresAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SignIn struct {
	ID           int64
	CustomerID   int64
	SignDate     pgtype.Date
	RewardAmount int64
	CreatedAt    pgtype.Timestamptz
}

type TaskClaim struct {
	ID            int64
	CustomerID    int64
	TaskID        int64
	Status        ClaimStatus
	ProofText     *string
	ProofImages   []string
	RewardBase    int64
	RewardGranted *int64
	ExpiresAt     pgtype.Timestamptz
	ClaimedAt     pgtype.Timestamptz
	SubmittedAt   pgtype.Timestamptz
	ReviewedBy    *int64
	ReviewedAt    pgtype.Timestamptz
	ReviewRemark  *string
	RewardedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID           int64
	CustomerID   int64
	Type         TransactionType
	Amount       int64
	BalanceAfter int64
	RefID        *int64
	CreatedAt    pgtype.Timestamptz
}

type TranscodeJob struct {
	ID         int64
	VideoID    int64
	Status     TranscodeJobStatus
	Attempts   int32
	LastError  *string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Video struct {
	ID             int64
	PublicID       string
	CustomerID     int64
	Title          string
	Tags           []string
	StoragePath    string
	HlsPath        *string
	ThumbnailPath  *string
	Duration       *int32
	Width          *int32
	Height         *int32
	FileSize       *int64
	MimeType       *string
	Status         VideoStatus
	ReviewedBy     *int64
	ReviewedAt     pgtype.Timestamptz
	ReviewNotes    *string
	ClickCount     int64
	ValidPlayCount int64
	LikeCount      int64
	CommentCount   int64
	HotScore       int64
	DeletedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type VipLevelConfig struct {
	Level              int32
	Name               string
	Price              int64
	RewardMultiplierBp int32
	InviteRewardCap    int64
	UpdatedAt          pgtype.Timestamptz
	UploadVideoLimit   int32
}

type VipPurchase struct {
	ID         int64
	CustomerID int64
	FromLevel  int32
	ToLevel    int32
	Price      int64
	CreatedAt  pgtype.Timestamptz
}

type Wallet struct {
	CustomerID int64
	Available  int64
	Frozen     int64
	UpdatedAt  pgtype.Timestamptz
}

type WatchProgressMark struct {
	CustomerID int64
	VideoID    int64
	PeriodKey  string
	CreatedAt  pgtype.Timestamptz
}

type WithdrawalOrder struct {
	ID              int64
	OrderNo         string
	CustomerID      int64
	Amount          int64
	FiatAmount      int64
	Currency        string
	BankCardID      *int64
	PayeeAccount    string
	PayeeName       string
	PayeeBank       *string
	PayeeBankCode   *string
	PayeeProvince   *string
	PayeeCity       *string
	Provider        *string
	ProviderOrderNo *string
	ProviderStatus  *string
	Status          WithdrawalOrderStatus
	ReviewedBy      *int64
	ReviewedAt      pgtype.Timestamptz
	RejectReason    *string
	FailureCode     *string
	FailureReason   *string
	CompletedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
