// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const finalizeRechargeOrderNo = `-- name: FinalizeRechargeOrderNo :one
UPDATE recharge_orders
SET order_no = 'R' || id, updated_at = now()
WHERE id = $1
RETURNING id, order_no, customer_id, amount, fiat_amount, currency, payment_method, provider, provider_order_no, provider_status, status, failure_code, failure_reason, expires_at, completed_at, created_at, updated_at
`

// 建单第二步：确定性派生 order_no = 'R'||id（与 InsertRechargeOrder 同事务）。
func (q *Queries) FinalizeRechargeOrderNo(ctx context.Context, id int64) (RechargeOrder, error) {
	row := q.db.QueryRow(ctx, finalizeRechargeOrderNo, id)
	var i RechargeOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.CustomerID,
		&i.Amount,
		&i.FiatAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Provider,
		&i.ProviderOrderNo,
		&i.ProviderStatus,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRechargeOrderByOrderNo = `-- name: GetRechargeOrderByOrderNo :one
SELECT id, order_no, customer_id, amount, fiat_amount, currency, payment_method, provider, provider_order_no, provider_status, status, failure_code, failure_reason, expires_at, completed_at, created_at, updated_at FROM recharge_orders WHERE order_no = $1
`

func (q *Queries) GetRechargeOrderByOrderNo(ctx context.Context, orderNo string) (RechargeOrder, error) {
	row := q.db.QueryRow(ctx, getRechargeOrderByOrderNo, orderNo)
	var i RechargeOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.CustomerID,
		&i.Amount,
		&i.FiatAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Provider,
		&i.ProviderOrderNo,
		&i.ProviderStatus,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRechargeOrderByProviderRef = `-- name: GetRechargeOrderByProviderRef :one
SELECT id, order_no, customer_id, amount, fiat_amount, currency, payment_method, provider, provider_order_no, provider_status, status, failure_code, failure_reason, expires_at, completed_at, created_at, updated_at FROM recharge_orders
WHERE provider = $1 AND provider_order_no = $2
`

type GetRechargeOrderByProviderRefParams struct {
	Provider        *string
	ProviderOrderNo *string
}

// 回调兜底定位：order_no 缺失时按 (provider, provider_order_no) 命中。
func (q *Queries) GetRechargeOrderByProviderRef(ctx context.Context, arg GetRechargeOrderByProviderRefParams) (RechargeOrder, error) {
	row := q.db.QueryRow(ctx, getRechargeOrderByProviderRef, arg.Provider, arg.ProviderOrderNo)
	var i RechargeOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.CustomerID,
		&i.Amount,
		&i.FiatAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Provider,
		&i.ProviderOrderNo,
		&i.ProviderStatus,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :exec
INSERT INTO payment_events (order_no, provider, direction, payload)
VALUES ($1, $2, $3, $4)
`

type InsertPaymentEventParams struct {
	OrderNo   string
	Provider  string
	Direction PaymentEventDirection
	Payload   []byte
}

// append-only 审计：每次 请求/响应/回调/查单 原始报文落库（资金纠纷佐证）。
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) error {
	_, err := q.db.Exec(ctx, insertPaymentEvent,
		arg.OrderNo,
		arg.Provider,
		arg.Direction,
		arg.Payload,
	)
	return err
}

const insertRechargeOrder = `-- name: InsertRechargeOrder :one
INSERT INTO recharge_orders (order_no, customer_id, amount, fiat_amount, payment_method, provider, expires_at)
VALUES (
    gen_random_uuid()::text,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id
`

type InsertRechargeOrderParams struct {
	CustomerID    int64
	Amount        int64
	FiatAmount    int64
	PaymentMethod *string
	Provider      *string
	ExpiresAt     pgtype.Timestamptz
}

// 建单第一步：先插入临时 order_no（uuid，避并发撞唯一索引），返回 IDENTITY id。
// 第二步 FinalizeRechargeOrderNo 在同事务内把 order_no 派生为确定性的 'R'||id。
func (q *Queries) InsertRechargeOrder(ctx context.Context, arg InsertRechargeOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRechargeOrder,
		arg.CustomerID,
		arg.Amount,
		arg.FiatAmount,
		arg.PaymentMethod,
		arg.Provider,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRechargeOrders = `-- name: ListRechargeOrders :many
SELECT id, order_no, customer_id, amount, fiat_amount, currency, payment_method, provider, provider_order_no, provider_status, status, failure_code, failure_reason, expires_at, completed_at, created_at, updated_at FROM recharge_orders
WHERE customer_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListRechargeOrdersParams struct {
	CustomerID int64
	Cursor     int64
	RowLimit   int32
}

func (q *Queries) ListRechargeOrders(ctx context.Context, arg ListRechargeOrdersParams) ([]RechargeOrder, error) {
	rows, err := q.db.Query(ctx, listRechargeOrders, arg.CustomerID, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RechargeOrder
	for rows.Next() {
		var i RechargeOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.CustomerID,
			&i.Amount,
			&i.FiatAmount,
			&i.Currency,
			&i.PaymentMethod,
			&i.Provider,
			&i.ProviderOrderNo,
			&i.ProviderStatus,
			&i.Status,
			&i.FailureCode,
			&i.FailureReason,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRechargeSucceeded = `-- name: MarkRechargeSucceeded :one
UPDATE recharge_orders
SET status = 'succeeded',
    provider_status = $1,
    completed_at = now(),
    updated_at = now()
WHERE id = $2 AND status = 'pending_payment'
RETURNING id, order_no, customer_id, amount, fiat_amount, currency, payment_method, provider, provider_order_no, provider_status, status, failure_code, failure_reason, expires_at, completed_at, created_at, updated_at
`

type MarkRechargeSucceededParams struct {
	ProviderStatus *string
	ID             int64
}

// 到账 CAS（幂等第二闸）：仅 pending_payment → succeeded；0 行 = 已终态，调用方短路。
func (q *Queries) MarkRechargeSucceeded(ctx context.Context, arg MarkRechargeSucceededParams) (RechargeOrder, error) {
	row := q.db.QueryRow(ctx, markRechargeSucceeded, arg.ProviderStatus, arg.ID)
	var i RechargeOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.CustomerID,
		&i.Amount,
		&i.FiatAmount,
		&i.Currency,
		&i.PaymentMethod,
		&i.Provider,
		&i.ProviderOrderNo,
		&i.ProviderStatus,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRechargeProviderInfo = `-- name: SetRechargeProviderInfo :exec
UPDATE recharge_orders
SET provider_order_no = $1,
    provider_status = $2,
    updated_at = now()
WHERE id = $3 AND status = 'pending_payment'
`

type SetRechargeProviderInfoParams struct {
	ProviderOrderNo *string
	ProviderStatus  *string
	ID              int64
}

// 建单调 Pay 后回填渠道单号/状态。仅在仍 pending_payment 时写——
// 防快速异步回调抢先落终态后，本回填把过期的 pending provider_status 盖回终态订单（P3）。
func (q *Queries) SetRechargeProviderInfo(ctx context.Context, arg SetRechargeProviderInfoParams) error {
	_, err := q.db.Exec(ctx, setRechargeProviderInfo, arg.ProviderOrderNo, arg.ProviderStatus, arg.ID)
	return err
}
