// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertDailyActive = `-- name: UpsertDailyActive :exec
INSERT INTO daily_actives (customer_id, active_date)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertDailyActiveParams struct {
	CustomerID int64
	ActiveDate pgtype.Date
}

func (q *Queries) UpsertDailyActive(ctx context.Context, arg UpsertDailyActiveParams) error {
	_, err := q.db.Exec(ctx, upsertDailyActive, arg.CustomerID, arg.ActiveDate)
	return err
}
