// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSignInsInMonth = `-- name: CountSignInsInMonth :one
SELECT COUNT(*) FROM sign_ins
WHERE customer_id = $1 AND date_trunc('month', sign_date) = date_trunc('month', $2::date)
`

type CountSignInsInMonthParams struct {
	CustomerID int64
	AnyDay     pgtype.Date
}

// 当月累计签到天数（自然月，date_trunc）。
func (q *Queries) CountSignInsInMonth(ctx context.Context, arg CountSignInsInMonthParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSignInsInMonth, arg.CustomerID, arg.AnyDay)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDailySignInReward = `-- name: GetDailySignInReward :one
SELECT reward FROM activity_reward_configs
WHERE kind = 'daily' AND threshold = 0 AND enabled
`

// 日签基础奖励：缺行或停用返回 ErrNoRows，调用方按"不发放"处理。
func (q *Queries) GetDailySignInReward(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDailySignInReward)
	var reward int64
	err := row.Scan(&reward)
	return reward, err
}

const getMilestoneReward = `-- name: GetMilestoneReward :one
SELECT reward FROM activity_reward_configs
WHERE kind = 'milestone' AND threshold = $1 AND enabled
`

// 里程碑档位奖励：threshold = 当月累计天数；缺行或停用返回 ErrNoRows（该天数不是里程碑）。
func (q *Queries) GetMilestoneReward(ctx context.Context, threshold int32) (int64, error) {
	row := q.db.QueryRow(ctx, getMilestoneReward, threshold)
	var reward int64
	err := row.Scan(&reward)
	return reward, err
}

const insertMilestoneAward = `-- name: InsertMilestoneAward :one
INSERT INTO milestone_awards (customer_id, month, threshold, reward_amount)
VALUES ($1, $2::date, $3, $4)
RETURNING id, customer_id, month, threshold, reward_amount, created_at
`

type InsertMilestoneAwardParams struct {
	CustomerID   int64
	Month        pgtype.Date
	Threshold    int32
	RewardAmount int64
}

// 里程碑发放：唯一约束 (customer_id, month, threshold) 幂等（同月同档只发一次）。
func (q *Queries) InsertMilestoneAward(ctx context.Context, arg InsertMilestoneAwardParams) (MilestoneAward, error) {
	row := q.db.QueryRow(ctx, insertMilestoneAward,
		arg.CustomerID,
		arg.Month,
		arg.Threshold,
		arg.RewardAmount,
	)
	var i MilestoneAward
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Month,
		&i.Threshold,
		&i.RewardAmount,
		&i.CreatedAt,
	)
	return i, err
}

const insertSignIn = `-- name: InsertSignIn :one
INSERT INTO sign_ins (customer_id, sign_date, reward_amount)
VALUES ($1, $2, $3)
RETURNING id, customer_id, sign_date, reward_amount, created_at
`

type InsertSignInParams struct {
	CustomerID   int64
	SignDate     pgtype.Date
	RewardAmount int64
}

// 日签：唯一约束 (customer_id, sign_date) 防重签；撞约束由调用方识别为"今日已签"。
func (q *Queries) InsertSignIn(ctx context.Context, arg InsertSignInParams) (SignIn, error) {
	row := q.db.QueryRow(ctx, insertSignIn, arg.CustomerID, arg.SignDate, arg.RewardAmount)
	var i SignIn
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.SignDate,
		&i.RewardAmount,
		&i.CreatedAt,
	)
	return i, err
}

const todaySigned = `-- name: TodaySigned :one
SELECT EXISTS (SELECT 1 FROM sign_ins WHERE customer_id = $1 AND sign_date = $2)::bool
`

type TodaySignedParams struct {
	CustomerID int64
	SignDate   pgtype.Date
}

func (q *Queries) TodaySigned(ctx context.Context, arg TodaySignedParams) (bool, error) {
	row := q.db.QueryRow(ctx, todaySigned, arg.CustomerID, arg.SignDate)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
