// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerRewardMultiplierBp = `-- name: GetCustomerRewardMultiplierBp :one
SELECT v.reward_multiplier_bp FROM customers c
JOIN vip_level_configs v ON v.level = c.vip_level
WHERE c.id = $1
`

func (q *Queries) GetCustomerRewardMultiplierBp(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getCustomerRewardMultiplierBp, id)
	var reward_multiplier_bp int32
	err := row.Scan(&reward_multiplier_bp)
	return reward_multiplier_bp, err
}

const grantTaskRewardIfDue = `-- name: GrantTaskRewardIfDue :execrows
UPDATE periodic_task_progress
SET completed_at = now(), reward_granted_at = now(),
    reward_amount = $1, updated_at = now()
WHERE id = $2 AND progress >= target AND reward_granted_at IS NULL
`

type GrantTaskRewardIfDueParams struct {
	RewardAmount *int64
	ID           int64
}

// 达标发奖翻转（幂等第二层）：reward_granted_at IS NULL 保证只发一次。
func (q *Queries) GrantTaskRewardIfDue(ctx context.Context, arg GrantTaskRewardIfDueParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantTaskRewardIfDue, arg.RewardAmount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isFirstValidPlayInPeriod = `-- name: IsFirstValidPlayInPeriod :one
SELECT (NOT EXISTS (
    SELECT 1 FROM plays p2
    WHERE p2.customer_id = $1
      AND p2.video_id = (SELECT p1.video_id FROM plays p1 WHERE p1.id = $2)
      AND p2.valid_at IS NOT NULL
      AND p2.valid_at >= $3
      AND p2.id < $2
))::bool
`

type IsFirstValidPlayInPeriodParams struct {
	CustomerID  int64
	PlayID      int64
	PeriodStart pgtype.Timestamptz
}

// watch 防刷：周期内该客户×该视频仅 id 最小的有效播放推进——并发上报下也恰好一次。
func (q *Queries) IsFirstValidPlayInPeriod(ctx context.Context, arg IsFirstValidPlayInPeriodParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFirstValidPlayInPeriod, arg.CustomerID, arg.PlayID, arg.PeriodStart)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listEnabledPeriodicTasks = `-- name: ListEnabledPeriodicTasks :many
SELECT id, name, description, icon_path, category, period, target, reward, display_order, enabled, deleted_at, created_at, updated_at FROM periodic_tasks
WHERE enabled AND deleted_at IS NULL
ORDER BY display_order, id
`

func (q *Queries) ListEnabledPeriodicTasks(ctx context.Context) ([]PeriodicTask, error) {
	rows, err := q.db.Query(ctx, listEnabledPeriodicTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconPath,
			&i.Category,
			&i.Period,
			&i.Target,
			&i.Reward,
			&i.DisplayOrder,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPeriodicTasksByCategory = `-- name: ListEnabledPeriodicTasksByCategory :many
SELECT id, name, description, icon_path, category, period, target, reward, display_order, enabled, deleted_at, created_at, updated_at FROM periodic_tasks
WHERE category = $1 AND enabled AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListEnabledPeriodicTasksByCategory(ctx context.Context, category TaskCategory) ([]PeriodicTask, error) {
	rows, err := q.db.Query(ctx, listEnabledPeriodicTasksByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconPath,
			&i.Category,
			&i.Period,
			&i.Target,
			&i.Reward,
			&i.DisplayOrder,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskProgressForKeys = `-- name: ListTaskProgressForKeys :many
SELECT id, customer_id, task_id, period_key, progress, target, completed_at, reward_granted_at, reward_amount, created_at, updated_at FROM periodic_task_progress
WHERE customer_id = $1 AND period_key = ANY($2::text[])
`

type ListTaskProgressForKeysParams struct {
	CustomerID int64
	PeriodKeys []string
}

func (q *Queries) ListTaskProgressForKeys(ctx context.Context, arg ListTaskProgressForKeysParams) ([]PeriodicTaskProgress, error) {
	rows, err := q.db.Query(ctx, listTaskProgressForKeys, arg.CustomerID, arg.PeriodKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTaskProgress
	for rows.Next() {
		var i PeriodicTaskProgress
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.TaskID,
			&i.PeriodKey,
			&i.Progress,
			&i.Target,
			&i.CompletedAt,
			&i.RewardGrantedAt,
			&i.RewardAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskProgress = `-- name: UpsertTaskProgress :one
INSERT INTO periodic_task_progress (customer_id, task_id, period_key, progress, target)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (customer_id, task_id, period_key) DO UPDATE
SET progress = periodic_task_progress.progress + 1, updated_at = now()
WHERE periodic_task_progress.progress < periodic_task_progress.target
RETURNING id, customer_id, task_id, period_key, progress, target, completed_at, reward_granted_at, reward_amount, created_at, updated_at
`

type UpsertTaskProgressParams struct {
	CustomerID int64
	TaskID     int64
	PeriodKey  string
	Target     int32
}

// 进度 +1：新周期首个事件懒建行（target 快照）；已达标不再累加（无更新即无行，调用方按封顶处理）。
func (q *Queries) UpsertTaskProgress(ctx context.Context, arg UpsertTaskProgressParams) (PeriodicTaskProgress, error) {
	row := q.db.QueryRow(ctx, upsertTaskProgress,
		arg.CustomerID,
		arg.TaskID,
		arg.PeriodKey,
		arg.Target,
	)
	var i PeriodicTaskProgress
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TaskID,
		&i.PeriodKey,
		&i.Progress,
		&i.Target,
		&i.CompletedAt,
		&i.RewardGrantedAt,
		&i.RewardAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
