// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveTaskClaim = `-- name: ApproveTaskClaim :one
UPDATE task_claims
SET status = 'rewarded', reviewed_by = $1, reviewed_at = now(),
    reward_granted = $2, rewarded_at = now(), updated_at = now()
WHERE id = $3 AND status = 'submitted'
RETURNING customer_id
`

type ApproveTaskClaimParams struct {
	ReviewedBy    *int64
	RewardGranted *int64
	ID            int64
}

// 审核即发奖一步：submitted→rewarded 单次条件 UPDATE，reviewed_*/rewarded_* 同落。
// 返回 customer_id 与实发额供同事务入账。
func (q *Queries) ApproveTaskClaim(ctx context.Context, arg ApproveTaskClaimParams) (int64, error) {
	row := q.db.QueryRow(ctx, approveTaskClaim, arg.ReviewedBy, arg.RewardGranted, arg.ID)
	var customer_id int64
	err := row.Scan(&customer_id)
	return customer_id, err
}

const expireClaims = `-- name: ExpireClaims :execrows
UPDATE task_claims
SET status = 'expired', updated_at = now()
WHERE expires_at IS NOT NULL AND expires_at < now()
  AND status IN ('claimed', 'rejected')
`

// 过期作废 {claimed, rejected}：待审核与已发奖豁免（cron 每 5 分钟）。
func (q *Queries) ExpireClaims(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireClaims)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClaimTask = `-- name: GetClaimTask :one
SELECT id, name, description, icon_path, min_vip_level, reward, requirement, flow, link, display_order, enabled, starts_at, ends_at, deleted_at, created_at, updated_at FROM claim_tasks WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClaimTask(ctx context.Context, id int64) (ClaimTask, error) {
	row := q.db.QueryRow(ctx, getClaimTask, id)
	var i ClaimTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IconPath,
		&i.MinVipLevel,
		&i.Reward,
		&i.Requirement,
		&i.Flow,
		&i.Link,
		&i.DisplayOrder,
		&i.Enabled,
		&i.StartsAt,
		&i.EndsAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimTaskForCustomer = `-- name: GetClaimTaskForCustomer :one
SELECT ct.id, ct.name, ct.icon_path, ct.min_vip_level, ct.reward,
       ct.requirement, ct.flow, ct.link, ct.starts_at, ct.ends_at, ct.deleted_at,
       tc.status AS claim_status
FROM claim_tasks ct
LEFT JOIN task_claims tc ON tc.task_id = ct.id AND tc.customer_id = $1
WHERE ct.id = $2
  AND ((ct.enabled AND ct.deleted_at IS NULL) OR tc.id IS NOT NULL)
`

type GetClaimTaskForCustomerParams struct {
	CustomerID int64
	ID         int64
}

type GetClaimTaskForCustomerRow struct {
	ID          int64
	Name        string
	IconPath    *string
	MinVipLevel int32
	Reward      int64
	Requirement *string
	Flow        *string
	Link        *string
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ClaimStatus NullClaimStatus
}

// 任务详情 + 查看者领取状态。可见性：上架未删的公开可见；已下架/软删的仅本人有领取记录时可看历史，
// 否则无行（404）——不向路人泄露已撤下的任务定义。
func (q *Queries) GetClaimTaskForCustomer(ctx context.Context, arg GetClaimTaskForCustomerParams) (GetClaimTaskForCustomerRow, error) {
	row := q.db.QueryRow(ctx, getClaimTaskForCustomer, arg.CustomerID, arg.ID)
	var i GetClaimTaskForCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IconPath,
		&i.MinVipLevel,
		&i.Reward,
		&i.Requirement,
		&i.Flow,
		&i.Link,
		&i.StartsAt,
		&i.EndsAt,
		&i.DeletedAt,
		&i.ClaimStatus,
	)
	return i, err
}

const getCustomerRewardMultiplierBp = `-- name: GetCustomerRewardMultiplierBp :one
SELECT v.reward_multiplier_bp FROM customers c
JOIN vip_level_configs v ON v.level = c.vip_level
WHERE c.id = $1
`

func (q *Queries) GetCustomerRewardMultiplierBp(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, getCustomerRewardMultiplierBp, id)
	var reward_multiplier_bp int32
	err := row.Scan(&reward_multiplier_bp)
	return reward_multiplier_bp, err
}

const getTaskClaim = `-- name: GetTaskClaim :one
SELECT id, customer_id, task_id, status, proof_text, proof_images, reward_base, reward_granted, expires_at, claimed_at, submitted_at, reviewed_by, reviewed_at, review_remark, rewarded_at, created_at, updated_at FROM task_claims WHERE id = $1
`

func (q *Queries) GetTaskClaim(ctx context.Context, id int64) (TaskClaim, error) {
	row := q.db.QueryRow(ctx, getTaskClaim, id)
	var i TaskClaim
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TaskID,
		&i.Status,
		&i.ProofText,
		&i.ProofImages,
		&i.RewardBase,
		&i.RewardGranted,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemark,
		&i.RewardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantTaskRewardIfDue = `-- name: GrantTaskRewardIfDue :execrows
UPDATE periodic_task_progress
SET completed_at = now(), reward_granted_at = now(),
    reward_amount = $1, updated_at = now()
WHERE id = $2 AND progress >= target AND reward_granted_at IS NULL
`

type GrantTaskRewardIfDueParams struct {
	RewardAmount *int64
	ID           int64
}

// 达标发奖翻转（幂等第二层）：reward_granted_at IS NULL 保证只发一次。
func (q *Queries) GrantTaskRewardIfDue(ctx context.Context, arg GrantTaskRewardIfDueParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantTaskRewardIfDue, arg.RewardAmount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTaskClaim = `-- name: InsertTaskClaim :one
INSERT INTO task_claims (customer_id, task_id, status, reward_base, expires_at)
VALUES ($1, $2, 'claimed', $3, $4)
RETURNING id, customer_id, task_id, status, proof_text, proof_images, reward_base, reward_granted, expires_at, claimed_at, submitted_at, reviewed_by, reviewed_at, review_remark, rewarded_at, created_at, updated_at
`

type InsertTaskClaimParams struct {
	CustomerID int64
	TaskID     int64
	RewardBase int64
	ExpiresAt  pgtype.Timestamptz
}

// 领取：一人一次由 (customer_id, task_id) 唯一约束保证；reward_base 与 expires_at 领取时快照。
func (q *Queries) InsertTaskClaim(ctx context.Context, arg InsertTaskClaimParams) (TaskClaim, error) {
	row := q.db.QueryRow(ctx, insertTaskClaim,
		arg.CustomerID,
		arg.TaskID,
		arg.RewardBase,
		arg.ExpiresAt,
	)
	var i TaskClaim
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TaskID,
		&i.Status,
		&i.ProofText,
		&i.ProofImages,
		&i.RewardBase,
		&i.RewardGranted,
		&i.ExpiresAt,
		&i.ClaimedAt,
		&i.SubmittedAt,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewRemark,
		&i.RewardedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClaimTasksForCustomer = `-- name: ListClaimTasksForCustomer :many
SELECT ct.id, ct.name, ct.icon_path, ct.min_vip_level, ct.reward,
       ct.requirement, ct.flow, ct.link, ct.starts_at, ct.ends_at,
       tc.status AS claim_status
FROM claim_tasks ct
LEFT JOIN task_claims tc ON tc.task_id = ct.id AND tc.customer_id = $1
WHERE ct.enabled AND ct.deleted_at IS NULL
ORDER BY ct.display_order, ct.id
`

type ListClaimTasksForCustomerRow struct {
	ID          int64
	Name        string
	IconPath    *string
	MinVipLevel int32
	Reward      int64
	Requirement *string
	Flow        *string
	Link        *string
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
	ClaimStatus NullClaimStatus
}

// 客户面可领取列表：启用未删的全部限时任务 + 查看者领取状态（三态分组在应用层算）。
func (q *Queries) ListClaimTasksForCustomer(ctx context.Context, customerID int64) ([]ListClaimTasksForCustomerRow, error) {
	rows, err := q.db.Query(ctx, listClaimTasksForCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClaimTasksForCustomerRow
	for rows.Next() {
		var i ListClaimTasksForCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IconPath,
			&i.MinVipLevel,
			&i.Reward,
			&i.Requirement,
			&i.Flow,
			&i.Link,
			&i.StartsAt,
			&i.EndsAt,
			&i.ClaimStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPeriodicTasks = `-- name: ListEnabledPeriodicTasks :many
SELECT id, name, description, icon_path, category, period, target, reward, display_order, enabled, deleted_at, created_at, updated_at FROM periodic_tasks
WHERE enabled AND deleted_at IS NULL
ORDER BY display_order, id
`

func (q *Queries) ListEnabledPeriodicTasks(ctx context.Context) ([]PeriodicTask, error) {
	rows, err := q.db.Query(ctx, listEnabledPeriodicTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconPath,
			&i.Category,
			&i.Period,
			&i.Target,
			&i.Reward,
			&i.DisplayOrder,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPeriodicTasksByCategory = `-- name: ListEnabledPeriodicTasksByCategory :many
SELECT id, name, description, icon_path, category, period, target, reward, display_order, enabled, deleted_at, created_at, updated_at FROM periodic_tasks
WHERE category = $1 AND enabled AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListEnabledPeriodicTasksByCategory(ctx context.Context, category TaskCategory) ([]PeriodicTask, error) {
	rows, err := q.db.Query(ctx, listEnabledPeriodicTasksByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTask
	for rows.Next() {
		var i PeriodicTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IconPath,
			&i.Category,
			&i.Period,
			&i.Target,
			&i.Reward,
			&i.DisplayOrder,
			&i.Enabled,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyClaims = `-- name: ListMyClaims :many
SELECT tc.id, tc.status, tc.reward_base, tc.reward_granted, tc.review_remark,
       tc.claimed_at, tc.rewarded_at, ct.name AS task_name
FROM task_claims tc
JOIN claim_tasks ct ON ct.id = tc.task_id
WHERE tc.customer_id = $1 AND tc.status::text = ANY($2::text[])
ORDER BY tc.id DESC
`

type ListMyClaimsParams struct {
	CustomerID int64
	Statuses   []string
}

type ListMyClaimsRow struct {
	ID            int64
	Status        ClaimStatus
	RewardBase    int64
	RewardGranted *int64
	ReviewRemark  *string
	ClaimedAt     pgtype.Timestamptz
	RewardedAt    pgtype.Timestamptz
	TaskName      string
}

// 我的领取记录：进行中 {claimed,submitted,rejected} / 已完成 {rewarded,expired}（id 降序）。
func (q *Queries) ListMyClaims(ctx context.Context, arg ListMyClaimsParams) ([]ListMyClaimsRow, error) {
	rows, err := q.db.Query(ctx, listMyClaims, arg.CustomerID, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyClaimsRow
	for rows.Next() {
		var i ListMyClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.RewardBase,
			&i.RewardGranted,
			&i.ReviewRemark,
			&i.ClaimedAt,
			&i.RewardedAt,
			&i.TaskName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingClaims = `-- name: ListPendingClaims :many
SELECT tc.id, tc.customer_id, tc.proof_text, tc.proof_images, tc.submitted_at,
       ct.name AS task_name, ct.requirement, tc.reward_base
FROM task_claims tc
JOIN claim_tasks ct ON ct.id = tc.task_id
WHERE tc.status = 'submitted' AND tc.id > $1
ORDER BY tc.id
LIMIT $2
`

type ListPendingClaimsParams struct {
	Cursor   int64
	RowLimit int32
}

type ListPendingClaimsRow struct {
	ID          int64
	CustomerID  int64
	ProofText   *string
	ProofImages []string
	SubmittedAt pgtype.Timestamptz
	TaskName    string
	Requirement *string
	RewardBase  int64
}

// 待审核队列（先进先出，id 升序游标）：附任务要求与凭证供管理员参考。
// 奖励取领取时快照 reward_base，与审核实际发奖口径一致（定义改 reward 不影响在途）。
func (q *Queries) ListPendingClaims(ctx context.Context, arg ListPendingClaimsParams) ([]ListPendingClaimsRow, error) {
	rows, err := q.db.Query(ctx, listPendingClaims, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingClaimsRow
	for rows.Next() {
		var i ListPendingClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProofText,
			&i.ProofImages,
			&i.SubmittedAt,
			&i.TaskName,
			&i.Requirement,
			&i.RewardBase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskProgressForKeys = `-- name: ListTaskProgressForKeys :many
SELECT id, customer_id, task_id, period_key, progress, target, completed_at, reward_granted_at, reward_amount, created_at, updated_at FROM periodic_task_progress
WHERE customer_id = $1 AND period_key = ANY($2::text[])
`

type ListTaskProgressForKeysParams struct {
	CustomerID int64
	PeriodKeys []string
}

func (q *Queries) ListTaskProgressForKeys(ctx context.Context, arg ListTaskProgressForKeysParams) ([]PeriodicTaskProgress, error) {
	rows, err := q.db.Query(ctx, listTaskProgressForKeys, arg.CustomerID, arg.PeriodKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicTaskProgress
	for rows.Next() {
		var i PeriodicTaskProgress
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.TaskID,
			&i.PeriodKey,
			&i.Progress,
			&i.Target,
			&i.CompletedAt,
			&i.RewardGrantedAt,
			&i.RewardAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWatchProgress = `-- name: MarkWatchProgress :execrows
INSERT INTO watch_progress_marks (customer_id, video_id, period_key)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type MarkWatchProgressParams struct {
	CustomerID int64
	VideoID    int64
	PeriodKey  string
}

// watch 防刷标记（推进事务内执行）：唯一约束仲裁并发，0 行 = 本周期该视频已计过。
func (q *Queries) MarkWatchProgress(ctx context.Context, arg MarkWatchProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWatchProgress, arg.CustomerID, arg.VideoID, arg.PeriodKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectTaskClaim = `-- name: RejectTaskClaim :execrows
UPDATE task_claims
SET status = 'rejected', reviewed_by = $1, reviewed_at = now(),
    review_remark = $2, updated_at = now()
WHERE id = $3 AND status = 'submitted'
`

type RejectTaskClaimParams struct {
	ReviewedBy   *int64
	ReviewRemark *string
	ID           int64
}

func (q *Queries) RejectTaskClaim(ctx context.Context, arg RejectTaskClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectTaskClaim, arg.ReviewedBy, arg.ReviewRemark, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submitTaskClaim = `-- name: SubmitTaskClaim :execrows
UPDATE task_claims
SET status = 'submitted', proof_text = $1,
    proof_images = $2, submitted_at = now(),
    reviewed_by = NULL, reviewed_at = NULL, review_remark = NULL, updated_at = now()
WHERE id = $3 AND customer_id = $4
  AND status IN ('claimed', 'rejected')
`

type SubmitTaskClaimParams struct {
	ProofText   *string
	ProofImages []string
	ID          int64
	CustomerID  int64
}

// 提交证明：claimed/rejected 可提交（驳回重提覆盖凭证回 submitted，清空上轮驳回痕迹）。
func (q *Queries) SubmitTaskClaim(ctx context.Context, arg SubmitTaskClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, submitTaskClaim,
		arg.ProofText,
		arg.ProofImages,
		arg.ID,
		arg.CustomerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertTaskProgress = `-- name: UpsertTaskProgress :one
INSERT INTO periodic_task_progress (customer_id, task_id, period_key, progress, target)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (customer_id, task_id, period_key) DO UPDATE
SET progress = periodic_task_progress.progress + 1, updated_at = now()
WHERE periodic_task_progress.progress < periodic_task_progress.target
RETURNING id, customer_id, task_id, period_key, progress, target, completed_at, reward_granted_at, reward_amount, created_at, updated_at
`

type UpsertTaskProgressParams struct {
	CustomerID int64
	TaskID     int64
	PeriodKey  string
	Target     int32
}

// 进度 +1：新周期首个事件懒建行（target 快照）；已达标不再累加（无更新即无行，调用方按封顶处理）。
func (q *Queries) UpsertTaskProgress(ctx context.Context, arg UpsertTaskProgressParams) (PeriodicTaskProgress, error) {
	row := q.db.QueryRow(ctx, upsertTaskProgress,
		arg.CustomerID,
		arg.TaskID,
		arg.PeriodKey,
		arg.Target,
	)
	var i PeriodicTaskProgress
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.TaskID,
		&i.PeriodKey,
		&i.Progress,
		&i.Target,
		&i.CompletedAt,
		&i.RewardGrantedAt,
		&i.RewardAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
