// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transcode.sql

package db

import (
	"context"
)

const claimTranscodeJob = `-- name: ClaimTranscodeJob :one
UPDATE transcode_jobs
SET status = 'running', started_at = now(), attempts = attempts + 1
WHERE id = (
    SELECT id FROM transcode_jobs
    WHERE status = 'queued'
    ORDER BY id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, video_id, status, attempts, last_error, started_at, finished_at, created_at
`

func (q *Queries) ClaimTranscodeJob(ctx context.Context) (TranscodeJob, error) {
	row := q.db.QueryRow(ctx, claimTranscodeJob)
	var i TranscodeJob
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const failTranscodeJob = `-- name: FailTranscodeJob :exec
UPDATE transcode_jobs SET status = 'failed', finished_at = now(), last_error = $2 WHERE id = $1
`

type FailTranscodeJobParams struct {
	ID        int64
	LastError *string
}

func (q *Queries) FailTranscodeJob(ctx context.Context, arg FailTranscodeJobParams) error {
	_, err := q.db.Exec(ctx, failTranscodeJob, arg.ID, arg.LastError)
	return err
}

const getVideoForTranscode = `-- name: GetVideoForTranscode :one
SELECT id, public_id, customer_id, title, tags, storage_path, hls_path, thumbnail_path, duration, width, height, file_size, mime_type, status, reviewed_by, reviewed_at, review_notes, click_count, valid_play_count, like_count, comment_count, hot_score, deleted_at, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideoForTranscode(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoForTranscode, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CustomerID,
		&i.Title,
		&i.Tags,
		&i.StoragePath,
		&i.HlsPath,
		&i.ThumbnailPath,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.MimeType,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.ClickCount,
		&i.ValidPlayCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.HotScore,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueStaleTranscodeJobs = `-- name: RequeueStaleTranscodeJobs :execrows
UPDATE transcode_jobs
SET status = 'queued'
WHERE status = 'running'
  AND started_at < now() - make_interval(secs => $1::int)
`

func (q *Queries) RequeueStaleTranscodeJobs(ctx context.Context, staleSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, requeueStaleTranscodeJobs, staleSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueTranscodeJob = `-- name: RequeueTranscodeJob :exec
UPDATE transcode_jobs SET status = 'queued', last_error = $2 WHERE id = $1
`

type RequeueTranscodeJobParams struct {
	ID        int64
	LastError *string
}

func (q *Queries) RequeueTranscodeJob(ctx context.Context, arg RequeueTranscodeJobParams) error {
	_, err := q.db.Exec(ctx, requeueTranscodeJob, arg.ID, arg.LastError)
	return err
}

const setVideoPendingTranscode = `-- name: SetVideoPendingTranscode :exec
UPDATE videos SET status = 'pending_transcode', updated_at = now()
WHERE id = $1 AND status = 'transcoding'
`

func (q *Queries) SetVideoPendingTranscode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setVideoPendingTranscode, id)
	return err
}

const setVideoTranscodeFailed = `-- name: SetVideoTranscodeFailed :exec
UPDATE videos SET status = 'transcode_failed', updated_at = now() WHERE id = $1
`

func (q *Queries) SetVideoTranscodeFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setVideoTranscodeFailed, id)
	return err
}

const setVideoTranscoded = `-- name: SetVideoTranscoded :exec
UPDATE videos
SET status = 'pending_review', hls_path = $2, thumbnail_path = $3,
    duration = $4, width = $5, height = $6, updated_at = now()
WHERE id = $1
`

type SetVideoTranscodedParams struct {
	ID            int64
	HlsPath       *string
	ThumbnailPath *string
	Duration      *int32
	Width         *int32
	Height        *int32
}

func (q *Queries) SetVideoTranscoded(ctx context.Context, arg SetVideoTranscodedParams) error {
	_, err := q.db.Exec(ctx, setVideoTranscoded,
		arg.ID,
		arg.HlsPath,
		arg.ThumbnailPath,
		arg.Duration,
		arg.Width,
		arg.Height,
	)
	return err
}

const setVideoTranscoding = `-- name: SetVideoTranscoding :exec
UPDATE videos SET status = 'transcoding', updated_at = now()
WHERE id = $1 AND status = 'pending_transcode'
`

func (q *Queries) SetVideoTranscoding(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setVideoTranscoding, id)
	return err
}

const succeedTranscodeJob = `-- name: SucceedTranscodeJob :exec
UPDATE transcode_jobs SET status = 'succeeded', finished_at = now() WHERE id = $1
`

func (q *Queries) SucceedTranscodeJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, succeedTranscodeJob, id)
	return err
}
