// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package db

import (
	"context"
)

const createTranscodeJob = `-- name: CreateTranscodeJob :one
INSERT INTO transcode_jobs (video_id) VALUES ($1)
RETURNING id, video_id, status, attempts, last_error, started_at, finished_at, created_at
`

func (q *Queries) CreateTranscodeJob(ctx context.Context, videoID int64) (TranscodeJob, error) {
	row := q.db.QueryRow(ctx, createTranscodeJob, videoID)
	var i TranscodeJob
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (public_id, customer_id, title, tags, storage_path)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, customer_id, title, tags, storage_path, hls_path, thumbnail_path, duration, width, height, file_size, mime_type, status, reviewed_by, reviewed_at, review_notes, click_count, valid_play_count, like_count, comment_count, hot_score, deleted_at, created_at, updated_at
`

type CreateVideoParams struct {
	PublicID    string
	CustomerID  int64
	Title       string
	Tags        []string
	StoragePath string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.PublicID,
		arg.CustomerID,
		arg.Title,
		arg.Tags,
		arg.StoragePath,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.CustomerID,
		&i.Title,
		&i.Tags,
		&i.StoragePath,
		&i.HlsPath,
		&i.ThumbnailPath,
		&i.Duration,
		&i.Width,
		&i.Height,
		&i.FileSize,
		&i.MimeType,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.ReviewNotes,
		&i.ClickCount,
		&i.ValidPlayCount,
		&i.LikeCount,
		&i.CommentCount,
		&i.HotScore,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
