// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vip.sql

package db

import (
	"context"
)

const getUploadLimitForCustomer = `-- name: GetUploadLimitForCustomer :one
SELECT v.upload_video_limit, c.video_count FROM customers c
JOIN vip_level_configs v ON v.level = c.vip_level
WHERE c.id = $1
`

type GetUploadLimitForCustomerRow struct {
	UploadVideoLimit int32
	VideoCount       int32
}

// 客户当前 VIP 档的发布作品上限与现存已发布作品数（confirm 拦截用）。
func (q *Queries) GetUploadLimitForCustomer(ctx context.Context, id int64) (GetUploadLimitForCustomerRow, error) {
	row := q.db.QueryRow(ctx, getUploadLimitForCustomer, id)
	var i GetUploadLimitForCustomerRow
	err := row.Scan(&i.UploadVideoLimit, &i.VideoCount)
	return i, err
}

const getVipLevelConfig = `-- name: GetVipLevelConfig :one
SELECT level, name, price, reward_multiplier_bp, invite_reward_cap, updated_at, upload_video_limit FROM vip_level_configs WHERE level = $1
`

func (q *Queries) GetVipLevelConfig(ctx context.Context, level int32) (VipLevelConfig, error) {
	row := q.db.QueryRow(ctx, getVipLevelConfig, level)
	var i VipLevelConfig
	err := row.Scan(
		&i.Level,
		&i.Name,
		&i.Price,
		&i.RewardMultiplierBp,
		&i.InviteRewardCap,
		&i.UpdatedAt,
		&i.UploadVideoLimit,
	)
	return i, err
}

const insertVipPurchase = `-- name: InsertVipPurchase :one
INSERT INTO vip_purchases (customer_id, from_level, to_level, price)
VALUES ($1, $2, $3, $4)
RETURNING id, customer_id, from_level, to_level, price, created_at
`

type InsertVipPurchaseParams struct {
	CustomerID int64
	FromLevel  int32
	ToLevel    int32
	Price      int64
}

func (q *Queries) InsertVipPurchase(ctx context.Context, arg InsertVipPurchaseParams) (VipPurchase, error) {
	row := q.db.QueryRow(ctx, insertVipPurchase,
		arg.CustomerID,
		arg.FromLevel,
		arg.ToLevel,
		arg.Price,
	)
	var i VipPurchase
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.FromLevel,
		&i.ToLevel,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const listVipLevelConfigs = `-- name: ListVipLevelConfigs :many
SELECT level, name, price, reward_multiplier_bp, invite_reward_cap, updated_at, upload_video_limit FROM vip_level_configs ORDER BY level
`

func (q *Queries) ListVipLevelConfigs(ctx context.Context) ([]VipLevelConfig, error) {
	rows, err := q.db.Query(ctx, listVipLevelConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VipLevelConfig
	for rows.Next() {
		var i VipLevelConfig
		if err := rows.Scan(
			&i.Level,
			&i.Name,
			&i.Price,
			&i.RewardMultiplierBp,
			&i.InviteRewardCap,
			&i.UpdatedAt,
			&i.UploadVideoLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upgradeVipLevel = `-- name: UpgradeVipLevel :one
WITH prev AS (
    SELECT vip_level FROM customers WHERE id = $2 FOR NO KEY UPDATE
)
UPDATE customers SET vip_level = $1, updated_at = now()
FROM prev
WHERE customers.id = $2 AND prev.vip_level < $1
RETURNING prev.vip_level AS from_level
`

type UpgradeVipLevelParams struct {
	ToLevel int32
	ID      int64
}

// 只升级 CAS：锁客户行并取旧档；仅当目标 > 当前才更新，0 行 = 降级/平级/不存在。
// 返回旧档供 vip_purchases 记录 from_level。
func (q *Queries) UpgradeVipLevel(ctx context.Context, arg UpgradeVipLevelParams) (int32, error) {
	row := q.db.QueryRow(ctx, upgradeVipLevel, arg.ToLevel, arg.ID)
	var from_level int32
	err := row.Scan(&from_level)
	return from_level, err
}
