// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package db

import (
	"context"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (customer_id) VALUES ($1)
`

func (q *Queries) CreateWallet(ctx context.Context, customerID int64) error {
	_, err := q.db.Exec(ctx, createWallet, customerID)
	return err
}
