// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: withdraw.sql

package db

import (
	"context"
)

const countActiveWithdrawalsByCard = `-- name: CountActiveWithdrawalsByCard :one
SELECT count(*) FROM withdrawal_orders
WHERE bank_card_id = $1
  AND status IN ('pending_review', 'paying')
`

func (q *Queries) CountActiveWithdrawalsByCard(ctx context.Context, bankCardID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWithdrawalsByCard, bankCardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalizeWithdrawalOrderNo = `-- name: FinalizeWithdrawalOrderNo :one
UPDATE withdrawal_orders
SET order_no = 'W' || id, updated_at = now()
WHERE id = $1
RETURNING id, order_no, customer_id, amount, fiat_amount, currency, bank_card_id, payee_account, payee_name, payee_bank, payee_bank_code, payee_province, payee_city, provider, provider_order_no, provider_status, status, reviewed_by, reviewed_at, reject_reason, failure_code, failure_reason, completed_at, created_at, updated_at
`

// 建单第二步：确定性派生 order_no = 'W'||id（与 InsertWithdrawalOrder 同事务）。
func (q *Queries) FinalizeWithdrawalOrderNo(ctx context.Context, id int64) (WithdrawalOrder, error) {
	row := q.db.QueryRow(ctx, finalizeWithdrawalOrderNo, id)
	var i WithdrawalOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.CustomerID,
		&i.Amount,
		&i.FiatAmount,
		&i.Currency,
		&i.BankCardID,
		&i.PayeeAccount,
		&i.PayeeName,
		&i.PayeeBank,
		&i.PayeeBankCode,
		&i.PayeeProvince,
		&i.PayeeCity,
		&i.Provider,
		&i.ProviderOrderNo,
		&i.ProviderStatus,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.RejectReason,
		&i.FailureCode,
		&i.FailureReason,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWithdrawalOrder = `-- name: InsertWithdrawalOrder :one
INSERT INTO withdrawal_orders (
    order_no, customer_id, amount, fiat_amount, bank_card_id,
    payee_account, payee_name, payee_bank, payee_bank_code, payee_province, payee_city
)
VALUES (
    gen_random_uuid()::text,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id
`

type InsertWithdrawalOrderParams struct {
	CustomerID    int64
	Amount        int64
	FiatAmount    int64
	BankCardID    *int64
	PayeeAccount  string
	PayeeName     string
	PayeeBank     *string
	PayeeBankCode *string
	PayeeProvince *string
	PayeeCity     *string
}

// 建单第一步：先插入临时 order_no（uuid，避并发撞唯一索引），返回 IDENTITY id。
// 第二步 FinalizeWithdrawalOrderNo 在同事务内把 order_no 派生为确定性的 'W'||id。
func (q *Queries) InsertWithdrawalOrder(ctx context.Context, arg InsertWithdrawalOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertWithdrawalOrder,
		arg.CustomerID,
		arg.Amount,
		arg.FiatAmount,
		arg.BankCardID,
		arg.PayeeAccount,
		arg.PayeeName,
		arg.PayeeBank,
		arg.PayeeBankCode,
		arg.PayeeProvince,
		arg.PayeeCity,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listWithdrawalOrders = `-- name: ListWithdrawalOrders :many
SELECT id, order_no, customer_id, amount, fiat_amount, currency, bank_card_id, payee_account, payee_name, payee_bank, payee_bank_code, payee_province, payee_city, provider, provider_order_no, provider_status, status, reviewed_by, reviewed_at, reject_reason, failure_code, failure_reason, completed_at, created_at, updated_at FROM withdrawal_orders
WHERE customer_id = $1
  AND ($2::bigint = 0 OR id < $2)
ORDER BY id DESC
LIMIT $3
`

type ListWithdrawalOrdersParams struct {
	CustomerID int64
	Cursor     int64
	RowLimit   int32
}

func (q *Queries) ListWithdrawalOrders(ctx context.Context, arg ListWithdrawalOrdersParams) ([]WithdrawalOrder, error) {
	rows, err := q.db.Query(ctx, listWithdrawalOrders, arg.CustomerID, arg.Cursor, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WithdrawalOrder
	for rows.Next() {
		var i WithdrawalOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.CustomerID,
			&i.Amount,
			&i.FiatAmount,
			&i.Currency,
			&i.BankCardID,
			&i.PayeeAccount,
			&i.PayeeName,
			&i.PayeeBank,
			&i.PayeeBankCode,
			&i.PayeeProvince,
			&i.PayeeCity,
			&i.Provider,
			&i.ProviderOrderNo,
			&i.ProviderStatus,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.RejectReason,
			&i.FailureCode,
			&i.FailureReason,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
